### ISSUE TITLE
wrong type with Subscription.current_billing_period

### ISSUE THREAD

**Issue by cnwangjie** [chargekit/paddle#1]
https://github.com/kossnocorp/paddle-billing/blob/062e82faf4ecf1981c0a6348a2a58c3598be7c94/src/types.ts#L272-L276

The type of `current_billing_period` should be an object with `starts_at` and `ends_at`

<img width="653" alt="image" src="https://github.com/kossnocorp/paddle-billing/assets/7459652/17de4e2f-3a1a-4fa7-a720-aba03d711fe8">

https://developer.paddle.com/api-reference/subscriptions/get-subscription

**Comment by kossnocorp** [comment]
Thank you for reporting that! Fixed in `paddle-billing@0.2.1`: https://github.com/kossnocorp/paddle-billing/commit/9e6141e386c3b7d52cc374ca348ab23f06d3736e
