### ISSUE TITLE
Missing `custom_data` field for some types

### ISSUE THREAD

**Issue by cnwangjie** [chargekit/paddle#2]
According to the paddle docs: https://developer.paddle.com/api-reference/about/custom-data#api. These types miss the `custom_data` field: Customer, Address, Business

**Comment by kossnocorp** [comment]
Thank you for reporting. It probably was added after I published the latest version. WIll add those too.

**Comment by kossnocorp** [comment]
Fixed and published as `paddle-billing@1.0.0`: https://github.com/kossnocorp/paddle-billing/blob/main/CHANGELOG.md#v100---2023-11-02
