### ISSUE TITLE
Types not discovered when using moduleResolution: bundler

### ISSUE THREAD

**Issue by jarle** [chargekit/paddle#5]
This library looks awesome! However, there are some issues with the package.json config for the types that you might want to be aware of.

When I import the package in a node.js project using modeResolution: bundler, I get this warning:

> Could not find a declaration file for module 'paddle-billing'. '[...]/node_modules/paddle-billing/index.mjs' implicitly has an 'any' type.
  There are types at '[...]/node_modules/paddle-billing/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'paddle-billing' library may need to update its package.json or typings.ts(7016)

It's discussed here: https://github.com/microsoft/TypeScript/issues/52363
And here is a tool someone built for checking types: https://arethetypeswrong.github.io/?p=paddle-billing%403.0.0

**Comment by kossnocorp** [comment]
Hey! I fixed such errors recently in date-fns, so I know what to do. I'll try to do this tomorrow morning. Thank you for the heads up!

**Comment by kossnocorp** [comment]
I fixed it with `paddle-billing@3.1.0`; please let me know if it helped.

**Comment by jarle** [comment]
It works perfectly now, thank you 🙌
