### ISSUE TITLE
How to pass Auth Token & Env Variable in Web API? 

### ISSUE THREAD

**Issue by pushkarsingh32** [chargekit/paddle#6]
Hi I was wondering if there is any way to pass auth token in web API? 

`const handlePurchase = (productId) => {
    loadScript().then((Paddle) => {
        Paddle.Checkout.open({
            settings: {
                displayMode: "overlay",
                theme: "light",
                locale: "en",
            },
            items: [
                {
                    priceId: productId, // use the product id from the parameter
                    quantity: 1,
                },
            ],
        });
    });
};`

**Comment by kossnocorp** [comment]
It depends on your environment. I'm using Next.js and pass it via `process.env`:

![image](https://github.com/kossnocorp/paddle-billing/assets/52201/aacef922-13fd-4a21-8a4a-93ff51fabcfa)
